development:
  adapter: postgresql
  encoding: unicode
  database: mobilebuddy_development
  pool: 5
  username: kerrymui
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: mobilebuddy_test
  pool: 5
  username: kerrymui
  password:
  host: localhost
  port: 5432
