development:
  adapter: postgresql
  encoding: unicode
  database: mobilebuddy_development
  pool: 5
  username: kerrymui
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mobilebuddy_test
  pool: 5
  username: kerrymui
  password:
